version: "3.8"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true

  api:
    extends:
      file: api/docker-compose.yaml
      service: api
    environment:
      - MONGO_URI=mongodb://mongodb:27017/api
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: docker/dockerfiles/postgres.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/certs:/var/lib/postgresql/certs
