name: pj-esc-001831

services:
  workspace:
    container_name: pj-esc-001831-workspace
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
