version: '3.8'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true

  api:
    extends:
      file: api/docker-compose.yaml
      service: api
    environment:
      - MONGO_URI=mongodb://mongodb:27017/api
    depends_on:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: docker/dockerfiles/mongodb.Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongodb/tmp/dumps:/tmp/backup/dumps